In [37]:
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=2)  # reduced display precision on numpy arrays

In [38]:
# 训练集
#       2104  5  1  45             460
# x =   1416  3  2  40       y =   232
#        852  2  1  35             178
X_train = np.array([[2104, 5, 1, 45], 
                    [1416, 3, 2, 40], 
                    [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [39]:
# 损失函数
def function_cost(X, y, w, b): 
    """
    compute cost
    Args:
      X (ndarray (m,n)): Data, m examples with n features
      y (ndarray (m,)) : target values
      w (ndarray (n,)) : model parameters  
      b (scalar)       : model parameter
      
    Returns:
      cost (scalar): cost
    """
    m = X.shape[0]
    cost = 0.0
    for i in range(m):                                
        f_wb_i = np.dot(X[i], w) + b           #(n,)(n,) = scalar (see np.dot)
        cost = cost + (f_wb_i - y[i])**2       #scalar
    cost = cost / (2 * m)                      #scalar    
    return cost

In [40]:
# 计算偏导数
def function_gradient(X, y, w, b):
    m,n = X.shape
    dj_dw = np.zeros((n,)) # 一行n列
    dj_db = 0.
    
    for i in range(m):
        error = np.dot(X[i], w) + b - y[i]
        for j in range(n):
            dj_dw[j] = dj_dw[j] + error * X[i, j]
        dj_db = dj_db + error
    
    dj_dw = dj_dw / m
    dj_db = dj_db / m
    
    return dj_dw, dj_db

In [41]:
def gradient_descent(X, y, w_star, b_star, alpha, iterations, cost_function, gradient_function):
    # 如果x为空，结束
    m = X.shape[0]
    if m == 0:
        return 0
    
    j_history = []
    w = w_star
    b = b_star
    
    for i in range(iterations):
        cost = cost_function(X, y, w, b)
        dj_w, dj_b = gradient_function(X, y, w, b)
        
        j_history.append(cost)
        w = w - alpha * dj_w
        b = b - alpha * dj_b
        
    return w, b, j_history

In [52]:
# 归一化
def Zscore_Normalization(X):
    x_mean = np.mean(X, axis=0)
    x_sigma = np.std(X, axis=0)
    x_norm = (X - x_mean) / x_sigma
    
    return x_norm

In [53]:
w_in = np.zeros(4)
b_in = 0.
iterations = 100000
alpha = 9e-7

# 归一化
X_norm = Zscore_Normalization(X_train)
print(X_train)
print(X_norm)

w_final, b_final, J_hist = gradient_descent(X_norm, y_train, w_in, b_in,alpha, iterations,
                                                    function_cost, function_gradient)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
[[ 1.26  1.34 -0.71  1.22]
 [-0.08 -0.27  1.41  0.  ]
 [-1.18 -1.07 -0.71 -1.22]]
b,w found by gradient descent: 24.96,[ 9.24  9.54 -3.42  9.06] 
prediction: 19920.50, target value: 460
prediction: 13494.73, target value: 232
prediction: 8231.26, target value: 178
